using System.Text;
using System.Text.RegularExpressions;

var file = File.ReadAllText("../../../inc/radiotap.h");

var builder = new StringBuilder();
builder.AppendLine(
    """
    // <auto-generated />
    
    using S1 = sbyte;
    using S2 = short;
    using S4 = int;
    using S8 = long;
    
    using U1 = byte;
    using U2 = ushort;
    using U4 = uint;
    using U8 = ulong;
    
    using size_t = nuint;
    
    using BOOL = byte;
    
    using System;
    using System.Runtime.InteropServices;
    
    namespace RTM.Models;
    
    """);
var tmp = new StringBuilder();
foreach (Match match in StructRegex().Matches(file))
{
    var fields = match.Groups["fields"];
    var tag    = match.Groups["tag"];

    tmp.Clear();
    foreach (var s in fields.Value.Split('\n', StringSplitOptions.RemoveEmptyEntries))
    {
        var line = s.TrimStart().Replace("struct tag__ctx_t", "Context");

        if (string.IsNullOrWhiteSpace(line))
        {
            tmp.AppendLine();
            continue;
        }
        
        tmp.Append("    public ");
        if (line.Contains('['))
            tmp.Append("fixed ");
        tmp.AppendLine(line);
    }
    
    builder.AppendLine(
        $$"""
          [Serializable]
          [StructLayout(LayoutKind.Sequential, Pack = 1)]
          public unsafe partial struct {{tag}}
          {
          {{tmp}}}
          
          """);
}

File.WriteAllText("../RTM/Models/Interop.g.cs", builder.ToString(), Encoding.UTF8);

internal partial class Program
{
    [GeneratedRegex(@"typedef struct\s*[^{]*\s*{(?<fields>[^}]+)}\s*(__field__)?(__pack__)?\s*(?<tag>[^;]+)")]
    private static partial Regex StructRegex();
}